# Generated by Django 4.1.1 on 2022-10-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="seccion",
            options={"verbose_name_plural": "Secciones"},
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="fecha",
        ),
    ]
